services:
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      - MYSQL_USER=${MYSQLDB_USER}
      - MYSQL_PASSWORD=${MYSQLDB_PASSWORD}
      - MYSQL_DATABASE=${MYSQLDB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQLDB_ROOT_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "${MYSQLDB_LOCAL_PORT:-3306}:${MYSQLDB_DOCKER_PORT:-3306}"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p${MYSQLDB_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 20s

  app:
    build: .
    image: master-quizz-app
    restart: on-failure
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "${SPRING_LOCAL_PORT:-8080}:${SPRING_DOCKER_PORT:-8080}"
      - "${DEBUG_PORT:-5005}:${DEBUG_PORT:-5005}"
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
      - MYSQLDB_URL=jdbc:mysql://mysql:${MYSQLDB_DOCKER_PORT:-3306}/${MYSQLDB_DATABASE}?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      - MYSQLDB_USER=${MYSQLDB_USER}
      - MYSQLDB_PASSWORD=${MYSQLDB_PASSWORD}
      - JAVA_TOOL_OPTIONS=-XX:TieredStopAtLevel=1 -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:${DEBUG_PORT:-5005}
      - SPRING_DATASOURCE_HIKARI_INITIALIZATION_FAIL_TIMEOUT=-1

volumes:
  mysql-data: