spring.config.import=optional:file:.env[.properties]

spring.application.name=MasterQuizz
spring.datasource.url=${MYSQLDB_URL}
spring.datasource.username=${MYSQLDB_USER}
spring.datasource.password=${MYSQLDB_PASSWORD}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=create
spring.liquibase.enabled=true